skip_tags: true
clone_depth: 1
pull_requests:
  do_not_increment_build_number: true

version: '{branch} build {build}'
image: Visual Studio 2015

environment:
  BOOST_ROOT: C:\Libraries\libboost

cache:
  - boost.cached -> appveyor.install.bat
  - C:\Libraries\libboost -> appveyor.install.bat

init:
  - git --version
  - git config --global core.autocrlf true

install:
  - .\appveyor.install.bat

build_script:
  - .\build.bat data hant

after_build:
  - appveyor.after_build.bat

artifacts:
  - path: output\archives\weasel-0.11.0.0-installer.exe
    name: Weasel
